from __future__ import annotations

import argparse
from dataclasses import asdict
from datetime import date
import json
import math
from pathlib import Path
from typing import Iterable, Literal

import numpy as np
import pandas as pd

from .data_loader import load_dataset
from .phase1 import audit_picking_locations
from .phase2 import calculate_demand_entropy
from .phase3 import (
    build_aisle_zones,
    classify_picking_lists_by_zone,
    macro_zone_demand_profiles,
    run_phase3_method,
    zone_workload,
)
from .phase4 import (
    DEFAULT_ENTROPY_WEIGHTS,
    Phase4CalibrationDateResult,
    build_entropy_candidates,
    extract_phase4_date_profiles,
)
from .progress import ConsoleProgress, format_duration
from .warehouse import WarehouseGraph


PHASE8_REVISION = "phase8-ai-adaptive-ewa-xgboost-v1"
DEFAULT_VALIDATION_RATIO = 0.20
DEFAULT_SEED = 42

TARGET_METRICS: tuple[str, ...] = (
    "mean_flow_time_seconds",
    "congestion_conflicts",
    "congestion_wait_seconds",
    "congestion_delay_ratio",
)
REPORT_METRICS: tuple[str, ...] = (
    *TARGET_METRICS,
    "makespan_seconds",
    "mean_release_delay_seconds",
)
KEY_COLUMNS: tuple[str, ...] = ("selected_date", "entropy_weight", "allocation_id")
ZONE_VALUE_COLUMNS: tuple[str, ...] = (
    "workload_share",
    "microzone_concentration",
    "workers",
    "worker_share",
)
BASE_FEATURE_COLUMNS: tuple[str, ...] = (
    "picking_lists",
    "pick_tasks",
    "picked_units",
    "effective_workers",
    "active_zones",
    "D_demand_mismatch",
    "R_congestion_risk",
    "moved_workers_from_volume",
)


class Phase8DependencyError(RuntimeError):
    """Raised when optional AI dependencies are not installed."""


def _require_ai_dependencies():
    try:
        from sklearn.ensemble import RandomForestRegressor
        from sklearn.linear_model import LinearRegression
        from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
        from xgboost import XGBRegressor
    except ImportError as exc:  # pragma: no cover - depends on local environment
        raise Phase8DependencyError(
            "Phase 8 AI 의존성이 없습니다. 프로젝트 루트에서 "
            "`python -m pip install -e .[ai]`를 먼저 실행하세요."
        ) from exc
    return {
        "LinearRegression": LinearRegression,
        "RandomForestRegressor": RandomForestRegressor,
        "XGBRegressor": XGBRegressor,
        "mean_absolute_error": mean_absolute_error,
        "mean_squared_error": mean_squared_error,
        "r2_score": r2_score,
    }


def _read_json(path: Path) -> dict[str, object]:
    if not path.exists():
        raise FileNotFoundError(path)
    with path.open("r", encoding="utf-8") as file:
        payload = json.load(file)
    if not isinstance(payload, dict):
        raise ValueError(f"JSON object가 필요합니다: {path}")
    return payload


def _required_columns(frame: pd.DataFrame, columns: Iterable[str], *, source: str) -> None:
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise ValueError(f"{source}에 필요한 컬럼이 없습니다: {', '.join(missing)}")


def _zone_ids_from_allocations(allocations: pd.DataFrame) -> tuple[str, ...]:
    values = sorted(str(value) for value in allocations["zone_id"].dropna().unique())
    if not values:
        raise ValueError("allocation 데이터에 zone_id가 없습니다.")
    return tuple(values)


def build_phase8_feature_dataset(
    daily: pd.DataFrame,
    allocations: pd.DataFrame,
    *,
    include_targets: bool = True,
) -> tuple[pd.DataFrame, tuple[str, ...]]:
    """Build leakage-safe tabular features from pre-simulation operating conditions.

    `entropy_weight` is deliberately NOT used as an ML feature. Lambda only creates
    a candidate integer worker vector; once the vector is fixed, DES performance is
    determined by the operating condition and allocation itself. This also makes
    identical allocations generated by different lambda values receive identical
    predictions, preventing a spurious direct lambda effect.
    """

    _required_columns(
        daily,
        (*KEY_COLUMNS, *BASE_FEATURE_COLUMNS),
        source="daily candidate results",
    )
    _required_columns(
        allocations,
        (*KEY_COLUMNS, "zone_id", *ZONE_VALUE_COLUMNS),
        source="candidate allocations",
    )
    if include_targets:
        _required_columns(daily, (*TARGET_METRICS, "makespan_seconds"), source="daily candidate results")

    keys = list(KEY_COLUMNS)
    base_columns = list(BASE_FEATURE_COLUMNS)
    optional_daily = [
        column
        for column in ("observed_workers", "mean_release_delay_seconds")
        if column in daily.columns
    ]
    feature_frame = daily[keys + base_columns + optional_daily].copy()

    zone_ids = _zone_ids_from_allocations(allocations)
    for value_column in ZONE_VALUE_COLUMNS:
        pivot = allocations.pivot_table(
            index=keys,
            columns="zone_id",
            values=value_column,
            aggfunc="first",
        )
        pivot = pivot.reindex(columns=zone_ids)
        pivot.columns = [f"{value_column}_{zone_id}" for zone_id in zone_ids]
        feature_frame = feature_frame.merge(pivot.reset_index(), on=keys, how="left", validate="one_to_one")

    effective = feature_frame["effective_workers"].astype(float).replace(0.0, np.nan)
    feature_frame["tasks_per_worker"] = feature_frame["pick_tasks"].astype(float) / effective
    feature_frame["units_per_worker"] = feature_frame["picked_units"].astype(float) / effective

    workload_columns = [f"workload_share_{zone_id}" for zone_id in zone_ids]
    concentration_columns = [f"microzone_concentration_{zone_id}" for zone_id in zone_ids]
    worker_columns = [f"workers_{zone_id}" for zone_id in zone_ids]

    feature_frame["max_workload_share"] = feature_frame[workload_columns].max(axis=1)
    feature_frame["max_workers_zone"] = feature_frame[worker_columns].max(axis=1)
    feature_frame["weighted_microzone_concentration"] = 0.0
    feature_frame["worker_concentration_pair"] = 0.0
    for zone_id in zone_ids:
        share = feature_frame[f"workload_share_{zone_id}"].astype(float)
        concentration = feature_frame[f"microzone_concentration_{zone_id}"].astype(float)
        workers = feature_frame[f"workers_{zone_id}"].astype(float)
        feature_frame["weighted_microzone_concentration"] += share * concentration
        feature_frame["worker_concentration_pair"] += concentration * (workers * (workers - 1.0) / 2.0)

    # Macro-zone workload entropy is available before DES and complements the
    # within-zone micro-demand concentration used by the EWA objective.
    shares = feature_frame[workload_columns].to_numpy(dtype=float)
    positive = np.where(shares > 0.0, shares, 1.0)
    entropy_bits = -np.where(shares > 0.0, shares * np.log2(positive), 0.0).sum(axis=1)
    active_counts = (shares > 0.0).sum(axis=1)
    denom = np.where(active_counts > 1, np.log2(active_counts), 1.0)
    feature_frame["macro_workload_entropy_normalized"] = np.where(
        active_counts > 1, entropy_bits / denom, 0.0
    )

    feature_columns = tuple(
        column
        for column in feature_frame.columns
        if column not in KEY_COLUMNS and column != "mean_release_delay_seconds"
    )

    if include_targets:
        target_columns = [*TARGET_METRICS]
        for optional_target in ("makespan_seconds", "mean_release_delay_seconds"):
            if optional_target in daily.columns:
                target_columns.append(optional_target)
        feature_frame = feature_frame.merge(
            daily[keys + target_columns],
            on=keys,
            how="left",
            validate="one_to_one",
            suffixes=("", "_target"),
        )
        # If mean_release_delay_seconds was carried as an optional daily column,
        # keep only its target version and never expose it as a model feature.
        if "mean_release_delay_seconds_target" in feature_frame.columns:
            feature_frame["mean_release_delay_seconds"] = feature_frame.pop(
                "mean_release_delay_seconds_target"
            )

    if feature_frame[list(feature_columns)].isna().any().any():
        bad = feature_frame[list(feature_columns)].columns[
            feature_frame[list(feature_columns)].isna().any()
        ].tolist()
        raise ValueError("Phase 8 feature에 결측값이 있습니다: " + ", ".join(bad))

    return feature_frame.sort_values(list(KEY_COLUMNS)).reset_index(drop=True), feature_columns


def chronological_date_split(
    frame: pd.DataFrame,
    *,
    validation_ratio: float = DEFAULT_VALIDATION_RATIO,
) -> tuple[tuple[str, ...], tuple[str, ...]]:
    dates = tuple(sorted(str(value) for value in frame["selected_date"].unique()))
    if len(dates) < 5:
        raise ValueError("Phase 8 내부 날짜 검증을 위해 calibration 날짜가 최소 5개 필요합니다.")
    ratio = float(validation_ratio)
    if not math.isfinite(ratio) or not (0.05 <= ratio <= 0.5):
        raise ValueError("validation_ratio는 0.05~0.5 범위여야 합니다.")
    validation_count = max(1, int(math.ceil(len(dates) * ratio)))
    validation_count = min(validation_count, len(dates) - 1)
    return dates[:-validation_count], dates[-validation_count:]


def _xgb_model(*, seed: int = DEFAULT_SEED):
    deps = _require_ai_dependencies()
    XGBRegressor = deps["XGBRegressor"]
    return XGBRegressor(
        n_estimators=500,
        max_depth=3,
        learning_rate=0.03,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_alpha=0.05,
        reg_lambda=1.0,
        objective="reg:squarederror",
        random_state=seed,
        n_jobs=4,
    )


def benchmark_models(
    frame: pd.DataFrame,
    feature_columns: tuple[str, ...],
    *,
    train_dates: Iterable[str],
    validation_dates: Iterable[str],
    seed: int = DEFAULT_SEED,
) -> pd.DataFrame:
    """Compare simple baselines with the designated XGBoost Phase-8 model."""

    deps = _require_ai_dependencies()
    LinearRegression = deps["LinearRegression"]
    RandomForestRegressor = deps["RandomForestRegressor"]
    mean_absolute_error = deps["mean_absolute_error"]
    mean_squared_error = deps["mean_squared_error"]
    r2_score = deps["r2_score"]

    train_set = set(str(value) for value in train_dates)
    validation_set = set(str(value) for value in validation_dates)
    train = frame[frame["selected_date"].astype(str).isin(train_set)]
    validation = frame[frame["selected_date"].astype(str).isin(validation_set)]
    if train.empty or validation.empty:
        raise ValueError("Phase 8 내부 학습/검증 데이터가 비어 있습니다.")

    records: list[dict[str, object]] = []
    for target in TARGET_METRICS:
        model_factories = {
            "linear_regression": lambda: LinearRegression(),
            "random_forest": lambda: RandomForestRegressor(
                n_estimators=400,
                min_samples_leaf=2,
                max_features=0.8,
                random_state=seed,
                n_jobs=-1,
            ),
            "xgboost": lambda: _xgb_model(seed=seed),
        }
        for model_name, factory in model_factories.items():
            model = factory()
            model.fit(train[list(feature_columns)], train[target])
            predicted = np.maximum(0.0, np.asarray(model.predict(validation[list(feature_columns)]), dtype=float))
            actual = validation[target].to_numpy(dtype=float)
            rmse = math.sqrt(float(mean_squared_error(actual, predicted)))
            records.append(
                {
                    "target": target,
                    "model": model_name,
                    "train_dates": len(train_set),
                    "validation_dates": len(validation_set),
                    "train_rows": len(train),
                    "validation_rows": len(validation),
                    "mae": float(mean_absolute_error(actual, predicted)),
                    "rmse": rmse,
                    "r2": float(r2_score(actual, predicted)),
                }
            )
    return pd.DataFrame(records)


def fit_xgboost_models(
    frame: pd.DataFrame,
    feature_columns: tuple[str, ...],
    *,
    dates: Iterable[str] | None = None,
    seed: int = DEFAULT_SEED,
) -> dict[str, object]:
    selected = frame
    if dates is not None:
        date_set = set(str(value) for value in dates)
        selected = frame[frame["selected_date"].astype(str).isin(date_set)]
    if selected.empty:
        raise ValueError("XGBoost 학습 데이터가 비어 있습니다.")
    models: dict[str, object] = {}
    for target in TARGET_METRICS:
        model = _xgb_model(seed=seed)
        model.fit(selected[list(feature_columns)], selected[target])
        models[target] = model
    return models


def predict_candidate_metrics(
    frame: pd.DataFrame,
    feature_columns: tuple[str, ...],
    models: dict[str, object],
) -> pd.DataFrame:
    result = frame[list(KEY_COLUMNS)].copy()
    for target in TARGET_METRICS:
        if target not in models:
            raise ValueError(f"학습 모델이 없습니다: {target}")
        predicted = np.asarray(models[target].predict(frame[list(feature_columns)]), dtype=float)
        result[f"predicted_{target}"] = np.maximum(0.0, predicted)
    return result


def _lambda0_relative_ratio(value: float, reference: float, *, fallback_scale: float) -> float:
    if abs(reference) > 1e-12:
        return value / reference
    if abs(value) <= 1e-12:
        return 1.0
    scale = fallback_scale if fallback_scale > 1e-12 else abs(value)
    return 1.0 + value / scale


def _nearest_lambda_row(frame: pd.DataFrame, weight: float) -> pd.Series:
    distances = (frame["entropy_weight"].astype(float) - float(weight)).abs()
    return frame.loc[distances.idxmin()]


def _congestion_index(
    frame: pd.DataFrame,
    *,
    prefix: str,
) -> pd.Series:
    zero = _nearest_lambda_row(frame, 0.0)
    components: list[pd.Series] = []
    for metric in ("congestion_conflicts", "congestion_wait_seconds", "congestion_delay_ratio"):
        column = f"{prefix}{metric}"
        reference = float(zero[column])
        scale = max(abs(float(value)) for value in frame[column])
        components.append(
            frame[column].astype(float).map(
                lambda value, _reference=reference, _scale=scale: _lambda0_relative_ratio(
                    float(value), _reference, fallback_scale=_scale
                )
            )
        )
    return sum(components) / len(components)


def _select_flow_guarded_candidate(
    frame: pd.DataFrame,
    *,
    fixed_lambda: float,
    predicted: bool,
) -> pd.Series:
    """Minimize congestion while keeping Flow no worse than fixed EWA.

    Primary Phase-8 decision rule:

        min C_hat(lambda)
        s.t. F_hat(lambda) <= F_hat(lambda_fixed)

    where lambda_fixed is the Phase-4 global Pareto-knee (0.25 in the current
    experiment). The oracle version applies the same rule to actual KPI values
    strictly for evaluation; it is never used to choose the AI action.
    """

    prefix = "predicted_" if predicted else ""
    flow_column = f"{prefix}mean_flow_time_seconds"
    fixed = _nearest_lambda_row(frame, fixed_lambda)
    fixed_flow = float(fixed[flow_column])
    eligible = frame[frame[flow_column].astype(float) <= fixed_flow + 1e-12].copy()
    if eligible.empty:
        return fixed
    eligible["_congestion_index"] = _congestion_index(frame, prefix=prefix).loc[eligible.index]
    return eligible.sort_values(
        ["_congestion_index", "entropy_weight"], ascending=[True, True]
    ).iloc[0]


def adaptive_selection_records(
    actual: pd.DataFrame,
    predictions: pd.DataFrame,
    *,
    fixed_lambda: float,
) -> pd.DataFrame:
    merged = actual.merge(predictions, on=list(KEY_COLUMNS), how="inner", validate="one_to_one")
    records: list[dict[str, object]] = []
    for selected_date, group in merged.groupby("selected_date", sort=True):
        fixed_row = _nearest_lambda_row(group, fixed_lambda)
        volume_row = _nearest_lambda_row(group, 0.0)
        ai_row = _select_flow_guarded_candidate(
            group,
            fixed_lambda=fixed_lambda,
            predicted=True,
        )
        oracle_row = _select_flow_guarded_candidate(
            group,
            fixed_lambda=fixed_lambda,
            predicted=False,
        )
        predicted_index = _congestion_index(group, prefix="predicted_")
        actual_index = _congestion_index(group, prefix="")
        record: dict[str, object] = {
            "selected_date": str(selected_date),
            "ai_entropy_weight": float(ai_row["entropy_weight"]),
            "fixed_entropy_weight": float(fixed_row["entropy_weight"]),
            "oracle_entropy_weight": float(oracle_row["entropy_weight"]),
            "ai_allocation_id": str(ai_row["allocation_id"]),
            "fixed_allocation_id": str(fixed_row["allocation_id"]),
            "volume_allocation_id": str(volume_row["allocation_id"]),
            "oracle_allocation_id": str(oracle_row["allocation_id"]),
            "ai_same_allocation_as_fixed": str(ai_row["allocation_id"]) == str(fixed_row["allocation_id"]),
            "ai_same_allocation_as_volume": str(ai_row["allocation_id"]) == str(volume_row["allocation_id"]),
            "ai_matches_oracle_lambda": math.isclose(
                float(ai_row["entropy_weight"]), float(oracle_row["entropy_weight"]), abs_tol=1e-12
            ),
            "ai_matches_oracle_allocation": str(ai_row["allocation_id"]) == str(oracle_row["allocation_id"]),
            "ai_predicted_congestion_index_lambda0": float(predicted_index.loc[ai_row.name]),
            "fixed_predicted_congestion_index_lambda0": float(predicted_index.loc[fixed_row.name]),
            "ai_actual_congestion_index_lambda0": float(actual_index.loc[ai_row.name]),
            "fixed_actual_congestion_index_lambda0": float(actual_index.loc[fixed_row.name]),
        }
        for target in TARGET_METRICS:
            record[f"ai_predicted_{target}"] = float(ai_row[f"predicted_{target}"])
            record[f"fixed_predicted_{target}"] = float(fixed_row[f"predicted_{target}"])
        for metric in REPORT_METRICS:
            if metric in group.columns:
                record[f"ai_{metric}"] = float(ai_row[metric])
                record[f"fixed_{metric}"] = float(fixed_row[metric])
                record[f"volume_{metric}"] = float(volume_row[metric])
                record[f"oracle_{metric}"] = float(oracle_row[metric])
        records.append(record)
    return pd.DataFrame(records)

def summarize_selection(selection: pd.DataFrame) -> pd.DataFrame:
    methods = ("ai", "fixed", "volume", "oracle")
    records: list[dict[str, object]] = []
    for metric in REPORT_METRICS:
        available = [method for method in methods if f"{method}_{metric}" in selection.columns]
        if not available:
            continue
        fixed_mean = float(selection[f"fixed_{metric}"].mean()) if "fixed" in available else float("nan")
        for method in available:
            mean_value = float(selection[f"{method}_{metric}"].mean())
            change_vs_fixed = (
                float("nan")
                if not math.isfinite(fixed_mean) or abs(fixed_mean) <= 1e-12
                else 100.0 * (mean_value - fixed_mean) / fixed_mean
            )
            records.append(
                {
                    "method": {
                        "ai": "ai_adaptive_ewa",
                        "fixed": "fixed_ewa",
                        "volume": "volume_lambda0",
                        "oracle": "oracle_flow_guarded",
                    }[method],
                    "metric": metric,
                    "mean": mean_value,
                    "change_vs_fixed_pct": change_vs_fixed,
                    "n_dates": len(selection),
                }
            )
    return pd.DataFrame(records)


def feature_importance_records(
    models: dict[str, object],
    feature_columns: tuple[str, ...],
) -> pd.DataFrame:
    records: list[dict[str, object]] = []
    for target, model in models.items():
        values = np.asarray(getattr(model, "feature_importances_", []), dtype=float)
        if len(values) != len(feature_columns):
            continue
        total = float(values.sum())
        for feature, value in zip(feature_columns, values, strict=True):
            records.append(
                {
                    "target": target,
                    "feature": feature,
                    "importance": float(value),
                    "importance_normalized": float(value / total) if total > 0.0 else 0.0,
                }
            )
    return pd.DataFrame(records).sort_values(
        ["target", "importance"], ascending=[True, False]
    ).reset_index(drop=True)


def build_holdout_candidate_inputs_from_phase5(
    phase5_daily: pd.DataFrame,
    phase5_allocations: pd.DataFrame,
    *,
    holdout_dates: Iterable[str],
    entropy_weights: Iterable[float],
    minimum_per_active_zone: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Create all holdout lambda candidate features from frozen Phase-5 inputs.

    No raw-data reload and no DES are needed. Phase 5 already persisted the exact
    date-level workload shares and micro-zone concentrations used by the frozen
    Holdout experiment, so Phase 8 can reconstruct every EWA integer candidate
    from those pre-simulation quantities without touching holdout outcomes.
    """

    requested = tuple(str(value) for value in holdout_dates)
    weights = tuple(float(value) for value in entropy_weights)
    _required_columns(
        phase5_daily,
        (
            "selected_date", "method", "picking_lists", "pick_tasks", "picked_units",
            "observed_workers", "effective_workers", "active_zones",
        ),
        source="phase5_daily_summary.csv",
    )
    _required_columns(
        phase5_allocations,
        (
            "selected_date", "method", "zone_id", "workload", "workload_share",
            "microzone_concentration",
        ),
        source="phase5_allocations.csv",
    )

    daily_records: list[dict[str, object]] = []
    allocation_records: list[dict[str, object]] = []
    for selected_date in requested:
        day_daily = phase5_daily[
            phase5_daily["selected_date"].astype(str).eq(selected_date)
            & phase5_daily["method"].eq("entropy_based")
        ]
        if len(day_daily) != 1:
            raise ValueError(f"Phase 5 entropy_based row가 유일하지 않습니다: {selected_date}")
        day = day_daily.iloc[0]
        day_alloc = phase5_allocations[
            phase5_allocations["selected_date"].astype(str).eq(selected_date)
            & phase5_allocations["method"].eq("entropy_based")
        ].copy().sort_values("zone_id")
        if day_alloc.empty:
            raise ValueError(f"Phase 5 allocation이 없습니다: {selected_date}")

        workloads = tuple(float(value) for value in day_alloc["workload"])
        concentrations = tuple(float(value) for value in day_alloc["microzone_concentration"])
        effective_workers = int(day["effective_workers"])
        candidates = build_entropy_candidates(
            total_workers=effective_workers,
            workloads=workloads,
            entropy_weights=weights,
            microzone_concentrations=concentrations,
            minimum_per_active_zone=minimum_per_active_zone,
        )
        total_workload = float(sum(workloads))
        zone_ids = tuple(str(value) for value in day_alloc["zone_id"])
        for candidate in candidates:
            daily_records.append(
                {
                    "selected_date": selected_date,
                    "entropy_weight": candidate.entropy_weight,
                    "allocation_id": candidate.allocation_id,
                    "worker_counts": "|".join(str(value) for value in candidate.worker_counts),
                    "picking_lists": int(day["picking_lists"]),
                    "pick_tasks": int(day["pick_tasks"]),
                    "picked_units": float(day["picked_units"]),
                    "observed_workers": int(day["observed_workers"]),
                    "effective_workers": effective_workers,
                    "active_zones": int(day["active_zones"]),
                    "D_demand_mismatch": candidate.demand_mismatch,
                    "R_congestion_risk": candidate.congestion_risk,
                    "J_objective": candidate.objective_value,
                    "moved_workers_from_volume": candidate.moved_workers_from_volume,
                }
            )
            total_candidate_workers = max(1, sum(candidate.worker_counts))
            for zone_id, workload, concentration, workers in zip(
                zone_ids,
                workloads,
                concentrations,
                candidate.worker_counts,
                strict=True,
            ):
                allocation_records.append(
                    {
                        "selected_date": selected_date,
                        "entropy_weight": candidate.entropy_weight,
                        "allocation_id": candidate.allocation_id,
                        "zone_id": zone_id,
                        "workload": workload,
                        "workload_share": workload / total_workload if total_workload > 0.0 else 0.0,
                        "microzone_concentration": concentration,
                        "workers": workers,
                        "worker_share": workers / total_candidate_workers,
                    }
                )
    return pd.DataFrame(daily_records), pd.DataFrame(allocation_records)

def predicted_selection_records(
    candidate_frame: pd.DataFrame,
    predictions: pd.DataFrame,
    *,
    fixed_lambda: float,
) -> pd.DataFrame:
    merged = candidate_frame.merge(
        predictions, on=list(KEY_COLUMNS), how="inner", validate="one_to_one"
    )
    records: list[dict[str, object]] = []
    for selected_date, group in merged.groupby("selected_date", sort=True):
        ai_row = _select_flow_guarded_candidate(
            group,
            fixed_lambda=fixed_lambda,
            predicted=True,
        )
        fixed_row = _nearest_lambda_row(group, fixed_lambda)
        predicted_index = _congestion_index(group, prefix="predicted_")
        record: dict[str, object] = {
            "selected_date": str(selected_date),
            "ai_entropy_weight": float(ai_row["entropy_weight"]),
            "ai_allocation_id": str(ai_row["allocation_id"]),
            "fixed_entropy_weight": float(fixed_row["entropy_weight"]),
            "fixed_allocation_id": str(fixed_row["allocation_id"]),
            "ai_predicted_congestion_index_lambda0": float(predicted_index.loc[ai_row.name]),
            "fixed_predicted_congestion_index_lambda0": float(predicted_index.loc[fixed_row.name]),
        }
        for target in TARGET_METRICS:
            record[f"ai_predicted_{target}"] = float(ai_row[f"predicted_{target}"])
            record[f"fixed_predicted_{target}"] = float(fixed_row[f"predicted_{target}"])
        records.append(record)
    return pd.DataFrame(records)


def _parse_worker_counts(value: object) -> tuple[int, ...]:
    parts = [part for part in str(value).split("|") if part != ""]
    if not parts:
        raise ValueError(f"worker_counts를 해석할 수 없습니다: {value!r}")
    return tuple(int(part) for part in parts)


def run_selected_holdout(
    data_dir: str | Path,
    *,
    selection: pd.DataFrame,
    candidate_daily: pd.DataFrame,
    phase5_daily: pd.DataFrame,
    min_lists_per_date: int,
    max_lists: int | None,
    number_of_zones: int,
    total_workers: int | None,
    volume_basis: Literal["tasks", "units"],
    minimum_per_active_zone: int,
    seed: int,
    walking_speed_mps: float,
    pick_seconds_per_unit: float,
    edge_capacity: int,
    pick_node_capacity: int,
    sample_seconds: float,
    return_to_io: bool,
    progress: ConsoleProgress | None,
) -> pd.DataFrame:
    """Run DES only for the AI-selected holdout allocation.

    Existing Phase-5 fixed/volume results are reused when the selected integer
    worker vector is identical. Otherwise exactly one new DES is run for that date.
    """

    _required_columns(
        phase5_daily,
        ("selected_date", "method", "worker_counts", *REPORT_METRICS),
        source="phase5_daily_summary.csv",
    )
    dataset = load_dataset(data_dir)
    warehouse = WarehouseGraph.build(
        dataset.storage_locations,
        dataset.support_points,
        deterministic_order=True,
    )
    audit_picking_locations(warehouse, dataset.picking_lists)
    zones = build_aisle_zones(warehouse, number_of_zones=number_of_zones)
    profiles, selected_by_date = extract_phase4_date_profiles(
        warehouse,
        dataset.picking_lists,
        zones,
        min_lists_per_date=min_lists_per_date,
        max_lists=max_lists,
        total_workers=total_workers,
        volume_basis=volume_basis,
        minimum_per_active_zone=minimum_per_active_zone,
    )
    profile_map = {profile.selected_date: profile for profile in profiles}

    records: list[dict[str, object]] = []
    for index, selected in selection.sort_values("selected_date").iterrows():
        selected_date_text = str(selected["selected_date"])
        selected_date = date.fromisoformat(selected_date_text)
        if selected_date not in selected_by_date or not profile_map[selected_date].eligible:
            raise ValueError(f"Holdout selected date를 실행할 수 없습니다: {selected_date_text}")

        candidate_match = candidate_daily[
            candidate_daily["selected_date"].astype(str).eq(selected_date_text)
            & candidate_daily["allocation_id"].astype(str).eq(str(selected["ai_allocation_id"]))
            & np.isclose(
                candidate_daily["entropy_weight"].astype(float),
                float(selected["ai_entropy_weight"]),
            )
        ]
        if candidate_match.empty:
            raise ValueError(f"AI selected candidate를 찾을 수 없습니다: {selected_date_text}")
        candidate_row = candidate_match.iloc[0]
        selected_counts = _parse_worker_counts(candidate_row["worker_counts"])

        p5_date = phase5_daily[phase5_daily["selected_date"].astype(str).eq(selected_date_text)]
        fixed_rows = p5_date[p5_date["method"].eq("entropy_based")]
        volume_rows = p5_date[p5_date["method"].eq("volume_proportional")]
        if len(fixed_rows) != 1 or len(volume_rows) != 1:
            raise ValueError(f"Phase 5 fixed/volume row가 유일하지 않습니다: {selected_date_text}")
        fixed = fixed_rows.iloc[0]
        volume = volume_rows.iloc[0]
        fixed_counts = _parse_worker_counts(fixed["worker_counts"])
        volume_counts = _parse_worker_counts(volume["worker_counts"])

        base_record: dict[str, object] = {
            "selected_date": selected_date_text,
            "ai_entropy_weight": float(selected["ai_entropy_weight"]),
            "ai_allocation_id": str(selected["ai_allocation_id"]),
            "ai_worker_counts": "|".join(str(value) for value in selected_counts),
            "fixed_worker_counts": "|".join(str(value) for value in fixed_counts),
            "volume_worker_counts": "|".join(str(value) for value in volume_counts),
        }
        if selected_counts == fixed_counts:
            source = "phase5_fixed_reuse"
            summary_record = fixed.to_dict()
        elif selected_counts == volume_counts:
            source = "phase5_volume_reuse"
            summary_record = volume.to_dict()
        else:
            source = "phase8_selected_des"
            selected_lists = selected_by_date[selected_date]
            assignments = classify_picking_lists_by_zone(warehouse, selected_lists, zones)
            demand_entropy, _ = calculate_demand_entropy(warehouse, selected_lists)
            if progress is not None:
                progress.report(
                    0.62 + 0.28 * (len(records) / max(1, len(selection))),
                    f"Phase 8D | Selected DES {selected_date_text}",
                    current=(
                        f"λ={float(selected['ai_entropy_weight']):g}, "
                        f"workers={base_record['ai_worker_counts']}"
                    ),
                )
            method_result = run_phase3_method(
                warehouse,
                selected_lists,
                zones,
                assignments,
                method=f"ai_adaptive_lambda_{float(selected['ai_entropy_weight']):g}",
                worker_counts=selected_counts,
                selected_date=selected_date,
                demand_entropy=demand_entropy,
                seed=seed,
                walking_speed_mps=walking_speed_mps,
                pick_seconds_per_unit=pick_seconds_per_unit,
                edge_capacity=edge_capacity,
                pick_node_capacity=pick_node_capacity,
                sample_seconds=sample_seconds,
                return_to_io=return_to_io,
                volume_basis=volume_basis,
            )
            summary_record = asdict(method_result.summary)
        base_record["actual_source"] = source
        for metric in REPORT_METRICS:
            base_record[metric] = float(summary_record[metric])
            base_record[f"fixed_{metric}"] = float(fixed[metric])
            base_record[f"volume_{metric}"] = float(volume[metric])
        records.append(base_record)
    return pd.DataFrame(records)


def summarize_holdout_selected(selected_actual: pd.DataFrame) -> pd.DataFrame:
    records: list[dict[str, object]] = []
    for metric in REPORT_METRICS:
        ai_mean = float(selected_actual[metric].mean())
        fixed_mean = float(selected_actual[f"fixed_{metric}"].mean())
        volume_mean = float(selected_actual[f"volume_{metric}"].mean())
        for method, mean_value in (
            ("ai_adaptive_ewa", ai_mean),
            ("fixed_ewa", fixed_mean),
            ("volume_lambda0", volume_mean),
        ):
            records.append(
                {
                    "method": method,
                    "metric": metric,
                    "mean": mean_value,
                    "change_vs_fixed_pct": (
                        100.0 * (mean_value - fixed_mean) / fixed_mean
                        if abs(fixed_mean) > 1e-12
                        else float("nan")
                    ),
                    "n_dates": len(selected_actual),
                }
            )
    return pd.DataFrame(records)

def save_xgboost_models(models: dict[str, object], output_dir: Path) -> None:
    model_dir = output_dir / "models"
    model_dir.mkdir(parents=True, exist_ok=True)
    for target, model in models.items():
        model.save_model(model_dir / f"xgboost_{target}.json")


def run_phase8(
    *,
    phase4_dir: str | Path = Path("results/phase4"),
    data_dir: str | Path = Path("data/raw"),
    phase5_dir: str | Path = Path("results/phase5"),
    output_dir: str | Path = Path("results/phase8"),
    train_only: bool = False,
    selection_only: bool = False,
    validation_ratio: float = DEFAULT_VALIDATION_RATIO,
    ai_seed: int = DEFAULT_SEED,
    progress: ConsoleProgress | None = None,
) -> dict[str, object]:
    phase4_dir = Path(phase4_dir)
    phase5_dir = Path(phase5_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    recommendation = _read_json(phase4_dir / "phase4_recommendation.json")
    phase4_metadata = _read_json(phase4_dir / "phase4_metadata.json")
    if str(recommendation.get("phase")) != "4E":
        raise ValueError("Phase 8은 Phase 4E recommendation이 필요합니다.")
    if str(recommendation.get("selection_rule")) != "pareto_knee":
        raise ValueError("Phase 8은 Pareto-knee 기반 Phase 4 결과를 요구합니다.")
    if str(recommendation.get("model_revision")) != str(phase4_metadata.get("model_revision")):
        raise ValueError("Phase 4 recommendation/metadata model_revision이 일치하지 않습니다.")

    parameters = phase4_metadata.get("parameters")
    if not isinstance(parameters, dict):
        raise ValueError("phase4_metadata.json에 Phase 4 실행 parameters가 없습니다.")

    fixed_lambda = float(recommendation["entropy_weight"])
    calibration_dates = tuple(str(value) for value in recommendation.get("calibration_dates", []))
    holdout_dates = tuple(str(value) for value in recommendation.get("holdout_dates", []))
    if not calibration_dates or not holdout_dates:
        raise ValueError("Phase 4 recommendation에 calibration/holdout 날짜가 없습니다.")

    # Phase 8 must preserve the Phase-4/5 DES environment. Only the AI model seed
    # is independent; warehouse/simulation parameters are frozen from Phase 4.
    min_lists_per_date = int(parameters.get("min_lists_per_date", 20))
    max_lists_raw = parameters.get("max_lists")
    max_lists = None if max_lists_raw is None else int(max_lists_raw)
    number_of_zones = int(parameters.get("zones", 4))
    workers_raw = parameters.get("workers")
    total_workers = None if workers_raw is None else int(workers_raw)
    volume_basis = str(parameters.get("volume_basis", "tasks"))
    if volume_basis not in {"tasks", "units"}:
        raise ValueError(f"지원하지 않는 Phase 4 volume_basis입니다: {volume_basis}")
    minimum_per_active_zone = int(parameters.get("minimum_per_active_zone", 1))
    simulation_seed = int(parameters.get("seed", 42))
    walking_speed_mps = float(parameters.get("walking_speed_mps", 1.2))
    pick_seconds_per_unit = float(parameters.get("pick_seconds_per_unit", 3.0))
    edge_capacity = int(parameters.get("edge_capacity", 1))
    pick_node_capacity = int(parameters.get("pick_node_capacity", 1))
    sample_seconds = float(parameters.get("sample_seconds", 5.0))
    return_to_io = bool(parameters.get("return_to_io", True))
    raw_weights = parameters.get("entropy_weights")
    if isinstance(raw_weights, list) and raw_weights:
        entropy_weights = tuple(float(value) for value in raw_weights)
    else:
        entropy_weights = DEFAULT_ENTROPY_WEIGHTS

    if progress is not None:
        progress.report(0.03, "Phase 8A | Loading Phase 4 calibration candidate results")
    calibration_daily = pd.read_csv(phase4_dir / "phase4_daily_results.csv")
    calibration_allocations = pd.read_csv(phase4_dir / "phase4_allocations.csv")
    feature_frame, feature_columns = build_phase8_feature_dataset(
        calibration_daily,
        calibration_allocations,
        include_targets=True,
    )
    observed_dates = tuple(sorted(feature_frame["selected_date"].astype(str).unique()))
    if observed_dates != tuple(sorted(calibration_dates)):
        raise ValueError(
            "Phase 4 calibration CSV 날짜와 recommendation 날짜가 일치하지 않습니다. "
            f"csv={len(observed_dates)}, recommendation={len(calibration_dates)}"
        )
    feature_frame.to_csv(output_dir / "phase8_training_dataset.csv", index=False)

    internal_train_dates, internal_validation_dates = chronological_date_split(
        feature_frame, validation_ratio=validation_ratio
    )
    if progress is not None:
        progress.report(0.10, "Phase 8A | Benchmarking Linear / RF / XGBoost by chronological dates")
    benchmark = benchmark_models(
        feature_frame,
        feature_columns,
        train_dates=internal_train_dates,
        validation_dates=internal_validation_dates,
        seed=ai_seed,
    )
    benchmark.to_csv(output_dir / "phase8_model_benchmark.csv", index=False)

    if progress is not None:
        progress.report(0.18, "Phase 8B | Internal date validation of adaptive lambda selection")
    internal_models = fit_xgboost_models(
        feature_frame,
        feature_columns,
        dates=internal_train_dates,
        seed=ai_seed,
    )
    internal_actual = feature_frame[
        feature_frame["selected_date"].astype(str).isin(set(internal_validation_dates))
    ].copy()
    internal_predictions = predict_candidate_metrics(
        internal_actual,
        feature_columns,
        internal_models,
    )
    internal_selection = adaptive_selection_records(
        internal_actual,
        internal_predictions,
        fixed_lambda=fixed_lambda,
    )
    internal_selection.to_csv(output_dir / "phase8_internal_validation_selection.csv", index=False)
    summarize_selection(internal_selection).to_csv(
        output_dir / "phase8_internal_validation_summary.csv", index=False
    )

    if progress is not None:
        progress.report(0.29, "Phase 8B | Refitting final XGBoost models on all calibration dates")
    final_models = fit_xgboost_models(feature_frame, feature_columns, seed=ai_seed)
    save_xgboost_models(final_models, output_dir)
    importance = feature_importance_records(final_models, feature_columns)
    importance.to_csv(output_dir / "phase8_feature_importance.csv", index=False)

    metadata: dict[str, object] = {
        "phase": 8,
        "revision": PHASE8_REVISION,
        "phase4_model_revision": recommendation.get("model_revision"),
        "purpose": "AI-adaptive lambda selection for Entropy-based Workforce Allocation with a fixed-EWA flow guardrail",
        "fixed_ewa_lambda": fixed_lambda,
        "ai_model": "XGBoost regression (one model per predicted KPI)",
        "model_benchmarks": ["linear_regression", "random_forest", "xgboost"],
        "target_metrics": list(TARGET_METRICS),
        "feature_columns": list(feature_columns),
        "lambda_is_model_feature": False,
        "lambda_role": (
            "lambda generates an integer EWA candidate allocation; XGBoost predicts DES KPIs from "
            "the operating condition and candidate allocation. Phase 8 then minimizes predicted "
            "congestion subject to predicted Flow Time not exceeding the fixed EWA candidate"
        ),
        "adaptive_selection_rule": (
            "min predicted congestion index subject to predicted mean Flow Time <= predicted "
            "Flow Time of the fixed Phase-4 EWA lambda on the same date"
        ),
        "data_leakage_control": (
            "internal validation is split by chronological operating date; rows from the same date "
            "never appear in both internal train and validation sets"
        ),
        "holdout_evaluation_guard": (
            "all holdout lambda candidates are feature-only before selection; AI lambda selection uses "
            "predicted KPI columns only, and DES is executed only for the selected integer allocation"
        ),
        "calibration_dates": list(calibration_dates),
        "internal_train_dates": list(internal_train_dates),
        "internal_validation_dates": list(internal_validation_dates),
        "frozen_holdout_dates": list(holdout_dates),
        "train_only": bool(train_only),
        "selection_only": bool(selection_only),
        "ai_parameters": {
            "validation_ratio": validation_ratio,
            "ai_seed": ai_seed,
        },
        "frozen_phase4_simulation_parameters": parameters,
    }

    if not train_only:
        phase5_metadata = _read_json(phase5_dir / "phase5_metadata.json")
        if int(phase5_metadata.get("phase", -1)) != 5:
            raise ValueError("Phase 8 최종 Holdout 비교에는 Phase 5 결과가 필요합니다.")
        if str(phase5_metadata.get("model_revision", "")) != str(
            recommendation.get("model_revision", "")
        ):
            raise ValueError("Phase 4/5 model_revision이 일치하지 않습니다.")
        frozen_phase5 = tuple(
            str(value) for value in phase5_metadata.get("holdout_dates_frozen", [])
        )
        completed_phase5 = tuple(
            str(value) for value in phase5_metadata.get("holdout_dates_completed", [])
        )
        skipped_phase5 = phase5_metadata.get("holdout_dates_skipped", [])
        if frozen_phase5 != holdout_dates or completed_phase5 != holdout_dates or skipped_phase5:
            raise ValueError(
                "Phase 8 최종 평가는 Phase 5 전체 frozen Holdout 40일 완료 결과가 필요합니다."
            )
        phase5_daily = pd.read_csv(phase5_dir / "phase5_daily_summary.csv")
        phase5_allocations = pd.read_csv(phase5_dir / "phase5_allocations.csv")

        if progress is not None:
            progress.report(0.40, "Phase 8C | Reconstructing all holdout lambda candidates from frozen Phase 5 inputs")
        candidate_daily, candidate_allocations = build_holdout_candidate_inputs_from_phase5(
            phase5_daily,
            phase5_allocations,
            holdout_dates=holdout_dates,
            entropy_weights=entropy_weights,
            minimum_per_active_zone=minimum_per_active_zone,
        )
        candidate_daily.to_csv(output_dir / "phase8_holdout_candidate_inputs.csv", index=False)
        candidate_allocations.to_csv(
            output_dir / "phase8_holdout_candidate_allocations.csv", index=False
        )
        holdout_feature_frame, holdout_feature_columns = build_phase8_feature_dataset(
            candidate_daily,
            candidate_allocations,
            include_targets=False,
        )
        if holdout_feature_columns != feature_columns:
            raise ValueError("Calibration/Holdout Phase 8 feature schema가 일치하지 않습니다.")
        holdout_predictions = predict_candidate_metrics(
            holdout_feature_frame,
            feature_columns,
            final_models,
        )
        holdout_predictions.to_csv(output_dir / "phase8_holdout_predictions.csv", index=False)
        holdout_selection = predicted_selection_records(
            holdout_feature_frame,
            holdout_predictions,
            fixed_lambda=fixed_lambda,
        )
        # Attach the discrete worker vector for transparency; this is still pre-DES.
        selected_counts = candidate_daily[
            ["selected_date", "entropy_weight", "allocation_id", "worker_counts"]
        ].drop_duplicates()
        holdout_selection = holdout_selection.merge(
            selected_counts,
            left_on=["selected_date", "ai_entropy_weight", "ai_allocation_id"],
            right_on=["selected_date", "entropy_weight", "allocation_id"],
            how="left",
            validate="one_to_one",
        ).drop(columns=["entropy_weight", "allocation_id"])
        holdout_selection = holdout_selection.rename(columns={"worker_counts": "ai_worker_counts"})
        holdout_selection.to_csv(output_dir / "phase8_holdout_selection.csv", index=False)
        metadata["adaptive_lambda_counts"] = {
            str(key): int(value)
            for key, value in holdout_selection["ai_entropy_weight"].value_counts().sort_index().items()
        }
        phase5_counts = phase5_daily[
            phase5_daily["method"].isin(["entropy_based", "volume_proportional"])
        ][["selected_date", "method", "worker_counts"]].copy()
        fixed_counts_map = dict(
            phase5_counts[phase5_counts["method"].eq("entropy_based")][
                ["selected_date", "worker_counts"]
            ].astype(str).itertuples(index=False, name=None)
        )
        volume_counts_map = dict(
            phase5_counts[phase5_counts["method"].eq("volume_proportional")][
                ["selected_date", "worker_counts"]
            ].astype(str).itertuples(index=False, name=None)
        )
        selected_worker_map = dict(
            holdout_selection[["selected_date", "ai_worker_counts"]]
            .astype(str)
            .itertuples(index=False, name=None)
        )
        reuse_counts = {"phase5_fixed_reuse": 0, "phase5_volume_reuse": 0, "phase8_selected_des": 0}
        for day, worker_counts in selected_worker_map.items():
            if worker_counts == fixed_counts_map.get(day):
                reuse_counts["phase5_fixed_reuse"] += 1
            elif worker_counts == volume_counts_map.get(day):
                reuse_counts["phase5_volume_reuse"] += 1
            else:
                reuse_counts["phase8_selected_des"] += 1
        metadata["predicted_selected_actual_source_counts"] = reuse_counts

        if selection_only:
            metadata["holdout_selection_completed"] = sorted(
                holdout_selection["selected_date"].astype(str).unique().tolist()
            )
        else:
            if progress is not None:
                progress.report(0.60, "Phase 8D | Executing selected holdout allocations only")
            selected_actual = run_selected_holdout(
                data_dir,
                selection=holdout_selection,
                candidate_daily=candidate_daily,
                phase5_daily=phase5_daily,
                min_lists_per_date=min_lists_per_date,
                max_lists=max_lists,
                number_of_zones=number_of_zones,
                total_workers=total_workers,
                volume_basis=volume_basis,  # type: ignore[arg-type]
                minimum_per_active_zone=minimum_per_active_zone,
                seed=simulation_seed,
                walking_speed_mps=walking_speed_mps,
                pick_seconds_per_unit=pick_seconds_per_unit,
                edge_capacity=edge_capacity,
                pick_node_capacity=pick_node_capacity,
                sample_seconds=sample_seconds,
                return_to_io=return_to_io,
                progress=progress,
            )
            selected_actual.to_csv(output_dir / "phase8_holdout_selected_actual.csv", index=False)
            holdout_summary = summarize_holdout_selected(selected_actual)
            holdout_summary.to_csv(output_dir / "phase8_holdout_comparison.csv", index=False)

            metadata["phase5_dir"] = str(phase5_dir)
            metadata["holdout_dates_completed"] = sorted(
                selected_actual["selected_date"].astype(str).unique().tolist()
            )
            metadata["selected_actual_source_counts"] = {
                str(key): int(value)
                for key, value in selected_actual["actual_source"].value_counts().items()
            }
    with (output_dir / "phase8_metadata.json").open("w", encoding="utf-8") as file:
        json.dump(metadata, file, ensure_ascii=False, indent=2, default=str)
    return metadata

def _fmt(value: float) -> str:
    return f"{float(value):,.4f}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Entropy Thesis - Phase 8 AI-Adaptive EWA: XGBoost KPI prediction + "
            "fixed-EWA flow-guarded adaptive lambda selection"
        )
    )
    parser.add_argument("--phase4-dir", type=Path, default=Path("results/phase4"))
    parser.add_argument("--data-dir", type=Path, default=Path("data/raw"))
    parser.add_argument("--phase5-dir", type=Path, default=Path("results/phase5"))
    parser.add_argument("--output-dir", type=Path, default=Path("results/phase8"))
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--train-only",
        action="store_true",
        help="Phase 4 calibration 학습/내부검증만 실행",
    )
    mode.add_argument(
        "--selection-only",
        action="store_true",
        help="Calibration 학습 + frozen Holdout λ 예측/선택까지만 실행하고 selected DES는 생략",
    )
    parser.add_argument("--validation-ratio", type=float, default=DEFAULT_VALIDATION_RATIO)
    parser.add_argument("--ai-seed", type=int, default=DEFAULT_SEED)
    args = parser.parse_args()

    progress = ConsoleProgress()
    progress.start("Phase 8 AI-Adaptive EWA")
    metadata = run_phase8(
        phase4_dir=args.phase4_dir,
        data_dir=args.data_dir,
        phase5_dir=args.phase5_dir,
        output_dir=args.output_dir,
        train_only=args.train_only,
        selection_only=args.selection_only,
        validation_ratio=args.validation_ratio,
        ai_seed=args.ai_seed,
        progress=progress,
    )
    progress.complete("Phase 8 processing completed")

    benchmark_path = args.output_dir / "phase8_model_benchmark.csv"
    benchmark = pd.read_csv(benchmark_path)
    print()
    print("=== Phase 8 | AI-Adaptive EWA ===")
    print(f"Fixed EWA lambda        : {float(metadata['fixed_ewa_lambda']):g}")
    print(f"Calibration dates       : {len(metadata['calibration_dates']):,}")
    print(f"Internal train dates    : {len(metadata['internal_train_dates']):,}")
    print(f"Internal validation     : {len(metadata['internal_validation_dates']):,}")
    print("AI model                : XGBoost")
    print("Lambda direct feature   : no (candidate allocation features only)")
    print("DES parameters          : frozen from Phase 4 metadata")
    print()
    print("=== Model Benchmark | Chronological Internal Validation ===")
    print("Target                         Model                 MAE          RMSE        R2")
    for row in benchmark.to_dict("records"):
        print(
            f"{str(row['target']):<30} {str(row['model']):<19} "
            f"{_fmt(row['mae']):>11}   {_fmt(row['rmse']):>11}   {_fmt(row['r2']):>8}"
        )

    if args.selection_only:
        print()
        print("=== Frozen Holdout | AI Selection Only (No New DES) ===")
        print(f"Adaptive lambda counts  : {metadata.get('adaptive_lambda_counts', {})}")
        print(f"Selected result sources : {metadata.get('predicted_selected_actual_source_counts', {})}")

    if not args.train_only and not args.selection_only:
        comparison = pd.read_csv(args.output_dir / "phase8_holdout_comparison.csv")
        print()
        print("=== Frozen Holdout | AI-Adaptive EWA vs Fixed EWA ===")
        pivot = comparison.pivot(index="metric", columns="method", values="mean")
        for metric in REPORT_METRICS:
            if metric not in pivot.index:
                continue
            ai_value = float(pivot.loc[metric, "ai_adaptive_ewa"])
            fixed_value = float(pivot.loc[metric, "fixed_ewa"])
            change = 100.0 * (ai_value - fixed_value) / fixed_value if abs(fixed_value) > 1e-12 else float("nan")
            print(
                f"{metric:<30} AI={ai_value:>11,.3f} | Fixed={fixed_value:>11,.3f} | "
                f"change={change:>8.3f}%"
            )
        print(f"Adaptive lambda counts  : {metadata.get('adaptive_lambda_counts', {})}")

    print()
    print(f"Results                 : {args.output_dir}")
    print(
        f"Total execution time    : {format_duration(progress.elapsed_seconds)} "
        f"({progress.elapsed_seconds:,.2f} s)"
    )


if __name__ == "__main__":
    main()
